/** BLOGPOSTPREVIEW */
export const BLOGPOSTPREVIEW_MAXWIDTH = "500px"
export const BLOGPOSTPREVIEW_MARGIN = "16px"
export const BLOGPOSTPREVIEW_MQ_PADDING = "8px"

export const BLOGPOSTPREVIEWUPPER_MARGINBOTTOM = "8px"
export const BLOGPOSTPREVIEWUPPER_BORDERRADIUS = "4px"
export const BLOGPOSTPREVIEWUPPER_BOXSHADOW = "4px 4px 4px rgba(0, 0, 0, 0.1)"

export const BLOGPOSTPREVIEWBODY_BG = "#f222ff"
export const BLOGPOSTPREVIEWBODY_BG_HOVERED = "linear-gradient(219deg, #8c1eff, #f222ff, #ff2975, #f222ff, #8c1eff)"
export const BLOGPOSTPREVIEWBODY_PADDING = "8px "

export const BLOGPOSTPREVIEWHEADLINE_FONTSIZE = "2.6rem"
export const BLOGPOSTPREVIEWHEADLINE_MARGINBOTTOM = "8px"

export const BLOGPOSTPREVIEWDATE_FONTSIZE = "1.4rem"

export const BLOGPOSTPREVIEWREADMORE_BORDERRADIUS = "4px"
export const BLOGPOSTPREVIEWREADMORE_PADDING = "8px"
export const BLOGPOSTPREVIEWREADMORE_WIDTH = "120px"
export const BLOGPOSTPREVIEWREADMORE_FONTSIZE = "1.4rem"
